enhancements:
  iceconcentration:
    name: IceConc
    operations:
      - name: colorize
        method: !!python/name:satpy.enhancements.colorize
        kwargs:
          palettes:
            - {
              values: [
                0,
                0.39 ,
                0.4 ,
                12.5 ,
                25,
                40 ,
                60 ,
                75 ,
                87.5 ,
                100
              ],
              colors: [
                [1,1,1,255],
                [1, 1, 1, 255],
                [255, 230, 255,255],
                [255, 1, 255,255],
                [1, 1, 255,255],
                [1, 255, 255,255],
                [1, 255, 1,255],
                [255, 255, 1,255],
                [255, 1, 1,255],
                [255, 255, 255,255]
              ]
              }
  icetemp:
    name: IceSrfTemp
    operations:
      - name: colorize
        method: !!python/name:satpy.enhancements.colorize
        kwargs:
          palettes:
            - {
              values: [
                0 ,
                230 ,
                240,
                250 ,
                260 ,
                270,
                280,
                300
              ],
              colors: [
                [1,1,1,255],
                [1,20,250,255],
                [1,170,251,255],
                [1,255,150,255],
                [25,255,60,255],
                [255,200,60,255],
                [255,1,1,255],
                [1,1,1,255]
                ]
               }
  icethick:
    name: IceThickness
    operations:
      - name: colorize
        method: !!python/name:satpy.enhancements.colorize
        kwargs:
          palettes:
            - {
              values: [ 0 , 0.001 , 1.0 , 1.5, 2.0, 2.5, 3.0, 3.5 , 4.0, 100 ],
              colors: [
                [1,1,1,255],
                [1,20,250,255],
                [1,180,250,255],
                [1,255,255,255],
                [1,255,120,255],
                [60,255,60,255],
                [160,255,60,255],
                [255,255,1,255],
                [255,1,1,255],
                [1,1,1,255]
                ]
               }
  iceage:
    name: IceAge
    operations:
      - name: colorize
        method: !!python/name:satpy.enhancements.colorize
        kwargs:
          palettes:
            - {
              values: [0,1,2,3,4.5,5,6,7,8 ],
              colors: [
                 [70,100,180,255],
                 [70,100,180,255],
                 [90,210,180,255],
                 [240,185,1,255],
                 [220,1,1,255],
                 [255,170,250,255],
                 [170,1,250,255],
                 [1,190,190,255],
                 [180,240,180,255]
                ]
               }
